using System;
using System.Collections.Generic;
using UnityEngine;

namespace TimelineKit
{
    /// <summary>
    /// Stores asset references declared by custom clips via ITimelineReferenceCollector.
    /// Generated by the PlayableDirectorEx Inspector button; consumed at runtime by
    /// PlayableDirectorEx.Preload() to warm assets into the loader cache before playback.
    /// </summary>
    [CreateAssetMenu(menuName = "Timeline Kit/Reference Manifest", fileName = "TimelineReferenceManifest")]
    public class TimelineReferenceManifest : ScriptableObject
    {
        [Tooltip("GUID of the source TimelineAsset.")]
        public string timelineGuid;

        [Tooltip("Asset path of the source TimelineAsset (e.g. Assets/Skills/Fireball.playable).")]
        public string timelinePath;

        [Tooltip("Assets declared by ITimelineReferenceCollector clips.")]
        public List<TimelineAssetReference> assetReferences = new();
    }

    /// <summary>One asset reference entry declared by a clip's ITimelineReferenceCollector.</summary>
    [Serializable]
    public class TimelineAssetReference
    {
        [Tooltip("Asset GUID (from AssetDatabase).")]
        public string assetGuid;

        [Tooltip("Full asset path (e.g. Assets/Prefabs/Fireball.prefab).")]
        public string assetPath;

        [Tooltip("Fully qualified C# type name of the asset.")]
        public string assetType;

        [Tooltip("Resources.Load key (non-empty only when the asset lives under Assets/Resources/).")]
        public string resourcePath;

        [Tooltip("Addressable address or key (empty if Addressables is not configured for this asset).")]
        public string addressableKey;

        [Tooltip("Name of the clip asset type that declared this reference.")]
        public string clipType;

        [Tooltip("Field name on the clip asset that holds this reference.")]
        public string fieldName;
    }
}
